// Each SVG preserves the original icon shape, centered in a square canvas.
export const iconAssets = {
  navHome: require("../../assets/icons/navigation/home.svg"),
  navCreate: require("../../assets/icons/navigation/create.svg"),
  navFamily: require("../../assets/icons/navigation/family.svg"),
  navExplore: require("../../assets/icons/navigation/explore.svg"),
  navLibrary: require("../../assets/icons/navigation/library.svg"),
  home: require("../../assets/icons/home.svg"),
  create: require("../../assets/icons/create.svg"),
  arrow: require("../../assets/icons/arrow.svg"),
  back: require("../../assets/icons/back.svg"),
  close: require("../../assets/icons/close.svg"),
  person: require("../../assets/icons/person.svg"),
  book: require("../../assets/icons/book.svg"),
  heart: require("../../assets/icons/heart.svg"),
  search: require("../../assets/icons/search.svg"),
  check: require("../../assets/icons/check.svg"),
  mic: require("../../assets/icons/mic.svg"),
  play: require("../../assets/icons/play.svg"),
  pause: require("../../assets/icons/pause.svg"),
  trash: require("../../assets/icons/trash.svg"),
  stop: require("../../assets/icons/stop.svg"),
  drag: require("../../assets/icons/drag.svg"),
  replay10: require("../../assets/icons/replay10.svg"),
  forward10: require("../../assets/icons/forward10.svg"),
  image: require("../../assets/icons/image.svg"),
  bear: require("../../assets/icons/bear.svg"),
  bluetooth: require("../../assets/icons/bluetooth.svg"),
  family: require("../../assets/icons/family.svg"),
} as const;
